# Generated by Django 5.2.4 on 2025-11-08 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(db_index=True, max_length=200, verbose_name='City name')),
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='City id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='city_photo/')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'indexes': [models.Index(fields=['city_name'], name='city_name_index')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Place id')),
                ('place_name', models.TextField(db_index=True, max_length=200, verbose_name='Place name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, upload_to='place_photo/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='goticket.city')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_name', models.CharField(db_index=True, max_length=200, verbose_name='Consert name')),
                ('concert_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Consert id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='concert_photo/')),
                ('cities', models.ManyToManyField(related_name='Conserts', to='goticket.city')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='goticket.place')),
            ],
            options={
                'verbose_name': 'Concert',
                'verbose_name_plural': 'Concerts',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(default=1, verbose_name='seat_number')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='goticket.place')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Singer id')),
                ('singer_name', models.CharField(db_index=True, max_length=200, verbose_name='Singer name')),
                ('event_time', models.DateField(verbose_name='Event time')),
                ('event_date', models.DateField(verbose_name='Event data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='singer_photo/')),
                ('consert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singers', to='goticket.concert')),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(db_index=True, max_length=100, verbose_name='Type of sport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sport_photo/')),
                ('cities', models.ManyToManyField(related_name='cities', to='goticket.city')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sports', to='goticket.place')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='sports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goticket.sport'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Club id')),
                ('event_time', models.DateField(verbose_name='Event time')),
                ('club_name', models.CharField(db_index=True, max_length=200, verbose_name='Club name')),
                ('event_date', models.DateField(verbose_name='Event data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='club_photo/')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sports', to='goticket.sport')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Seat number')),
                ('is_sold', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goticket.cart')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='goticket.ticket')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['full_name', 'phone', 'email'], name='name_phone_email_index'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['concert_name'], name='concert_name_index'),
        ),
        migrations.AddIndex(
            model_name='singer',
            index=models.Index(fields=['singer_name', 'event_time', 'event_date'], name='singer_event_time_date_index'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['sport_name'], name='sport_name_index'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_name'], name='place_name_index'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['club_name', 'event_date', 'event_time'], name='name_time_date_index'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='category_index'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'seat_number'), name='unique_seat'),
        ),
    ]
