# Generated by Django 5.2.4 on 2025-11-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='consert',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sports',
        ),
        migrations.AddField(
            model_name='club',
            name='cities',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='goticket.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='places',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='goticket.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='singer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conserts', to='goticket.singer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='clubs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='goticket.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='goticket.cart'),
        ),
        migrations.RemoveField(
            model_name='concert',
            name='cities',
        ),
        migrations.AlterField(
            model_name='concert',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conserts', to='goticket.place'),
        ),
        migrations.AddField(
            model_name='concert',
            name='cities',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conserts', to='goticket.city'),
            preserve_default=False,
        ),
    ]
