# Generated by Django 5.2.4 on 2025-09-01 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consert',
            name='cities',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(db_index=True, max_length=200, verbose_name='Consert name')),
                ('concert_id', models.CharField(max_length=200, verbose_name='Consert id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='concert_photo/')),
                ('cities', models.ManyToManyField(related_name='conserts', to='goticket.city')),
            ],
            options={
                'verbose_name': 'Concert',
                'verbose_name_plural': 'Concerts',
            },
        ),
        migrations.AlterField(
            model_name='singer',
            name='consert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singers', to='goticket.concert'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['concert_name'], name='concert_name_index'),
        ),
        migrations.DeleteModel(
            name='Consert',
        ),
    ]
