# Generated by Django 5.2.4 on 2025-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0002_remove_club_sport_remove_place_sports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='event_time',
            field=models.DateTimeField(verbose_name='Event time'),
        ),
    ]
