# Generated by Django 5.2.4 on 2025-10-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0002_remove_consert_cities_user_role_concert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='goticket.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='sports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goticket.sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='sports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Places', to='goticket.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sports', to='goticket.sport'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='cities',
            field=models.ManyToManyField(related_name='Conserts', to='goticket.city'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='cities',
            field=models.ManyToManyField(related_name='Sports', to='goticket.city'),
        ),
    ]
