# Generated by Django 5.2.4 on 2025-12-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0003_alter_singer_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='event_time',
            field=models.TimeField(verbose_name='Event time'),
        ),
    ]
