# Generated by Django 5.2.4 on 2025-12-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0004_alter_singer_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='place',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/user_photo/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/city_photo/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/club_photo/'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/concert_photo/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/place_photo/'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/singer_photo/'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/sport_photo/'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
