# Generated by Django 5.2.4 on 2026-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0005_remove_cartitem_cart_remove_cartitem_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket id'),
        ),
    ]
