# Generated by Django 5.2.4 on 2026-09-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goticket', '0006_remove_ticket_id_ticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='clubs',
        ),
        migrations.AddField(
            model_name='club',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='goticket.sport'),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/place_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/user_photo/'),
        ),
    ]
