# Generated by Django 5.2.4 on 2026-09-19 17:15

import django.db.models.deletion
import goticket.models
from django.db import migrations, models


def normalize_blank_seats(apps, schema_editor):
    Ticket = apps.get_model('goticket', 'Ticket')
    Ticket.objects.filter(seat_number='').update(seat_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goticket', '0008_ticket_buyer'),
    ]

    operations = [
        migrations.RunPython(normalize_blank_seats, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to=goticket.models.limit_ticket_content_type,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(
                condition=models.Q(('seat_number__isnull', False)),
                fields=('content_type', 'object_id', 'seat_number'),
                name='unique_seat',
            ),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['content_type', 'object_id'], name='ticket_event_index'),
        ),
    ]
