# Generated by Django 5.2.4 on 2026-09-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goticket', '0011_place_capacity_ticket_currency_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Row')),
                ('number', models.PositiveIntegerField(verbose_name='Seat number')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['section', 'row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan A401, B408, Fan-zona', max_length=20, verbose_name='Section name')),
                ('category', models.CharField(choices=[('VIP', 'VIP'), ('Standart', 'Standart')], default='Standart', max_length=20, verbose_name='category')),
                ('rows', models.PositiveIntegerField(default=10, verbose_name='Rows')),
                ('seats_per_row', models.PositiveIntegerField(default=20, verbose_name='Seats per row')),
                ('row_layout', models.CharField(blank=True, help_text='Ixtiyoriy: har qatordagi o‘rindiqlar soni vergul bilan (20,22,24). To‘ldirilsa Rows va Seats per row o‘rniga ishlatiladi.', max_length=500, verbose_name='Row layout')),
                ('map_x', models.DecimalField(blank=True, decimal_places=2, help_text='Sxema rasmida sektor joyi: chapdan foizda (0–100)', max_digits=5, null=True, verbose_name='Map X %')),
                ('map_y', models.DecimalField(blank=True, decimal_places=2, help_text='Sxema rasmida sektor joyi: tepadan foizda (0–100)', max_digits=5, null=True, verbose_name='Map Y %')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='scheme',
            field=models.ImageField(blank=True, help_text='Stadion sxemasi rasmi (sektorlar ko‘rinadigan rasm)', null=True, upload_to='photos/place_scheme/', verbose_name='Stadium scheme'),
        ),
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Sektorlardagi o‘rindiqlardan avtomatik hisoblanadi', verbose_name='Seat capacity'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Seat number'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='goticket.seat', verbose_name='Seat'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('seat__isnull', False)), fields=('content_type', 'object_id', 'seat'), name='unique_ticket_seat'),
        ),
        migrations.AddField(
            model_name='section',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='goticket.place'),
        ),
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='goticket.section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('place', 'name'), name='unique_place_section'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('section', 'row', 'number'), name='unique_section_seat'),
        ),
    ]
